version: "3"

services:
  chat-frontend:
    tty: true
    build:
      context: frontend
      dockerfile: Dockerfile
    restart: always
    container_name: chat-frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/:/usr/src/app
    networks:
      - chat-network
    depends_on:
      - chat-database
      - chat-database-express
      - chat-backend

  chat-backend:
    build:
      context: backend
      dockerfile: Dockerfile
    restart: always
    container_name: chat-backend
    ports:
      - 4000:4000
    volumes:
      - ./backend/:/usr/src/app
    networks:
      - chat-network
    depends_on:
      - chat-database
      - chat-database-express

  chat-database:
    image: mongo
    container_name: chat-database
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./.docker/dbdata:/data/db
#    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    networks:
      - chat-network

  chat-database-express:
    image: mongo-express
    container_name: chat-database-interface-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_SERVER: chat-database
    networks:
      - chat-network
    depends_on:
      - chat-database

networks:
  chat-network:
    driver: bridge